build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/bc_20    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bc     1 20
build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/bfs_20   configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bfs    1 20
build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/cc_20    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  cc     1 20
build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/pr_20    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  pr     1 20
build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/tc_20    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  tc     1 20
build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/cpt/sssp_20  configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  sssp   1 20


# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/bc_20    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bc    1 20  ../../results/cptTest/GAPBS_Ram/cpt/bc_20/cpt
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/bfs_20   configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bfs   1 20  ../../results/cptTest/GAPBS_Ram/cpt/bfs_20/cpt
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/cc_20    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  cc    1 20  ../../results/cptTest/GAPBS_Ram/cpt/cc_20/cpt
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/pr_20    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  pr    1 20  ../../results/cptTest/GAPBS_Ram/cpt/pr_20/cpt
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/tc_20    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  tc    1 20  ../../results/cptTest/GAPBS_Ram/cpt/tc_20/cpt
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/GAPBS_Ram/rstr/sssp_20  configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  sssp  1 20  ../../results/cptTest/GAPBS_Ram/cpt/sssp_20/cpt