  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/bt_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level bt.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/cg_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level cg.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/ep_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level ep.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/is_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level is.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/lu_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level lu.C.x  8 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/mg_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level mg.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/cpt/sp_C_x  configs-npb-small/run_npb_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level sp.C.x  8 &


  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/bt_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level bt.C.x  8 ../../results/cptTest/NPB/cpt/bt_C_x/cpt &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/cg_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level cg.C.x  8 ../../results/cptTest/NPB/cpt/cg_C_x/cpt &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/ep_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level ep.C.x  8 ../../results/cptTest/NPB/cpt/ep_C_x/cpt &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/is_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level is.C.x  8 ../../results/cptTest/NPB/cpt/is_C_x/cpt &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/lu_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level lu.C.x  8 ../../results/cptTest/NPB/cpt/lu_C_x/cpt &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/mg_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level mg.C.x  8 ../../results/cptTest/NPB/cpt/mg_C_x/cpt &
  build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/cptTest/NPB/rstr/sp_C_x   configs-npb-small/run_npb_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-npb timing MESI_Two_Level sp.C.x  8 ../../results/cptTest/NPB/cpt/sp_C_x/cpt &



# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/bc_22    configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bc     1 22 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/bfs_22   configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bfs    1 22 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/cc_22    configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  cc     1 22 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/pr_22    configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  pr     1 22 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/tc_22    configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  tc     1 22 &
# build/X86_MESI_Two_Level/gem5.opt  --outdir=../../results/GAPBS/cptTest/sssp_22  configs-gapbs-small/run_gapbs.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  sssp   1 22 &