  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/bt_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level bt.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/cg_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level cg.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/ep_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level ep.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/is_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level is.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/lu_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level lu.C.x  8 &
# build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/mg_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level mg.C.x  8 &
  build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/NPB/set2/sp_C_x configsMemCtrl/configs-npb-small/run_npb.py configsMemCtrl/configs-npb-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-npb-small/x86-npb timing MESI_Two_Level sp.C.x  8 &

build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/GAPBS/set2/bc_20  configsMemCtrl/configs-gapbs-small/run_gapbs.py configsMemCtrl/configs-gapbs-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-gapbs-small/x86-gapbs  timing 8 MESI_Two_Level  bc   1 20 &
build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/GAPBS/set2/bfs_20 configsMemCtrl/configs-gapbs-small/run_gapbs.py configsMemCtrl/configs-gapbs-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-gapbs-small/x86-gapbs  timing 8 MESI_Two_Level  bfs  1 20 &
build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/GAPBS/set2/cc_20  configsMemCtrl/configs-gapbs-small/run_gapbs.py configsMemCtrl/configs-gapbs-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-gapbs-small/x86-gapbs  timing 8 MESI_Two_Level  cc   1 20 &
build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/GAPBS/set2/pr_20  configsMemCtrl/configs-gapbs-small/run_gapbs.py configsMemCtrl/configs-gapbs-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-gapbs-small/x86-gapbs  timing 8 MESI_Two_Level  pr   1 20 &
build/X86_MESI_Two_Level/gem5.opt --outdir=results/memCtrl/GAPBS/set2/tc_20  configsMemCtrl/configs-gapbs-small/run_gapbs.py configsMemCtrl/configs-gapbs-small/x86-linux-kernel-4.19.83 configsMemCtrl/configs-gapbs-small/x86-gapbs  timing 8 MESI_Two_Level  tc   1 20 &